name: Update Language Stats

on:
  push:
    branches:
      - main

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 14
          nvm use 14

      - name: Debug Environment Variables
        run: |
          echo "GitHub Repository Owner: ${{ github.repository_owner }}"
          echo "GitHub Repository Name: ${{ github.event.repository.name }}"
          echo "GitHub Token: $GH_TOKEN"
          echo "Path: $GITHUB_WORKSPACE"

      - name: Install github-lang
        run: npm install -g github-lang

      - name: Update Language Stats
        run: github-lang -r ${{ github.repository_owner }}/${{ github.event.repository.name }} -t $GH_TOKEN
